#!/usr/bin/env python3
"""
Setup script to create .env file for OCR API keys.
"""

import os
from pathlib import Path

def create_env_file():
    """Create a .env file with API key configuration."""
    
    print("🔧 OCR API Configuration Setup")
    print("=" * 40)
    
    # Check if .env already exists
    env_file = Path(".env")
    if env_file.exists():
        print("⚠️ .env file already exists!")
        overwrite = input("Do you want to overwrite it? (y/N): ").strip().lower()
        if overwrite not in ['y', 'yes']:
            print("⏹️ Setup cancelled.")
            return
    
    print("\n📝 Enter your Mistral API key:")
    print("   Get your API key from: https://console.mistral.ai/")
    mistral_key = input("Mistral API Key: ").strip()
    
    if not mistral_key:
        print("❌ Mistral API key is required!")
        return
    
    # Create .env file content
    env_content = f"""# OCR API Configuration
# Generated by setup script

# Mistral API Key for OCR processing
MISTRAL_API_KEY={mistral_key}

# Google Cloud credentials are handled via the JSON file
# GOOGLE_APPLICATION_CREDENTIALS is set in the code
"""
    
    # Write .env file
    try:
        with open(env_file, 'w') as f:
            f.write(env_content)
        
        print(f"\n✅ .env file created successfully!")
        print(f"📁 Location: {env_file.absolute()}")
        print("\n🔒 Security Note:")
        print("   - Keep your .env file secure and never commit it to version control")
        print("   - The .env file is already added to .gitignore")
        
    except Exception as e:
        print(f"❌ Error creating .env file: {e}")

def main():
    """Main function."""
    print("🚀 OCR API Setup")
    print("=" * 20)
    
    # Check if we're in the right directory
    if not Path("categorized_batch_ocr.py").exists():
        print("❌ Please run this script from the google_vision directory")
        return
    
    create_env_file()

if __name__ == "__main__":
    main()
